# Generated by Django 2.2.4 on 2019-09-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='User',
            new_name='WUser',
        ),
    ]
